---
name: Lint

'on':
  workflow_dispatch:
  push:
    branches:
      - 'ci-*'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  merge_group:

permissions: {}

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          cache: 'pnpm'
          node-version: lts/*
      - name: Install Node.js dependencies
        run: pnpm install --frozen-lockfile
      - name: Check lint/prettier errors
        run: pnpm run lint
      - name: Check taplo
        run: pnpm run lint:taplo
