---
name: PR - i18n Checks

'on':
    workflow_dispatch:
    push:
        branches:
            - 'ci-*'
    pull_request:
        types:
            - opened
            - reopened
            - synchronize
    merge_group:

concurrency:
    # https://docs.github.com/en/actions/examples/using-concurrency-expressions-and-a-test-matrix
    group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
    cancel-in-progress: ${{ !startsWith(github.ref, 'refs/tags/v') || github.ref != 'refs/heads/development' || github.ref != 'refs/heads/nextnet' || github.ref != 'refs/heads/stagenet' }}

permissions: {}

jobs:
    i18n-checks:
        name: i18n-checks
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: install jsonlint
              run: |
                  sudo apt-get update
                  sudo apt-get install --no-install-recommends --assume-yes \
                    python3-demjson

            - name: basic jsonlint
              run: |
                  find public -iname '*.json'  -print0 | \
                    xargs -0 -n1 jsonlint -v

            - name: setup folder for logs
              run: |
                  mkdir -p ${{ runner.temp }}/i18n_logs

            - name: i18n compare
              continue-on-error: true
              working-directory: ./public/locales
              run: |
                  python3 ../../scripts/i18n_checker.py \
                    compare --en-locale-path en \
                    --base-path . \
                    --search-path .. \
                    --output-dir ${{ runner.temp }}/i18n_logs

            - name: i18n unused
              continue-on-error: true
              working-directory: ./public/locales
              run: |
                  python3 ../../scripts/i18n_checker.py \
                    unused --en-locale-path en \
                    --base-path . \
                    --search-path .. \
                    --output-dir ${{ runner.temp }}/i18n_logs

            - name: Artifact upload for i18n checks
              uses: actions/upload-artifact@v4
              with:
                  name: i18n-logs
                  path: ${{ runner.temp }}/i18n_logs
