---
# Checks if the comments are signed or not
name: PR - Signed commits check

'on':
  pull_request_target

permissions: {}

jobs:
  check-signed-commits:
    name: Check signed commits in PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check signed commits in PR
        uses: 1Password/check-signed-commits-action@v1
